version: '3'
services:
  # grafana:
  #   image: "grafana/grafana"
  #   ports:
  #     - "3001:3000"
  #   links:
  #     - influxdb:influxdb
  #   volumes:
  #     - ./grafana:/var/lib/grafana
  influxgraph:
    build: ../
    links:
      - influxdb:influxdb
    ports:
      - "8300:80"
    volumes:
      - ./graphite-api.yaml:/etc/graphite-api.yaml:ro
      - ../../:/srv/influxgraph

  influxdb:
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_GRAPHITE_ENABLED: "true"
      # INFLUXDB_GRAPHITE_TEMPLATES: "measurement*.field"
      INFLUXDB_GRAPHITE_DATABASE: "telegraf"
    image: "influxdb"
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - ./influxdb:/var/lib/influxdb
  telegraf:
    hostname: apphost
    links:
      - influxdb:influxdb
    image: "telegraf"
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"

    volumes:
      - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro


  chronograf:
    hostname: chronograf
    links:
      - influxdb:influxdb
    image: "chronograf"
    ports:
      - "8888:8888"
    command: --influxdb-url=http://influxdb:8086