version: '3'
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3001:3000"
    links:
      - influxdb:influxdb
    volumes:
      - ./grafana:/var/lib/grafana
  influxgraph2:
    image: influxgraph2
    links:
      - influxdb:influxdb
    ports:
      - "80:80"
  influxdb:
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_GRAPHITE_TEMPLATES: "measurement.field*"
      INFLUXDB_GRAPHITE_DATABASE: "telegraf"
    image: "influxdb"
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - ./influxdb:/var/lib/influxdb
  telegraf:
    hostname: apphost
    links:
      - influxdb:influxdb
    image: "telegraf"
    volumes:
      - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
